import React from "react";
import Head from "next/head";
import { Layout } from "../components/Layout";
import { Pokemon } from "../interfaces/pokemon";
import SearchInput from "../components/SearchInput";
import PowerThresholdInput from "../components/PowerThresholdInput";
import PaginationControls from "../components/PaginationControls";
import StatsDisplay from "../components/StatsDisplay";
import PokemonTable from "../components/PokemonTable";
import { useFilteredPokemons } from "../hooks/useFilteredPokemons";
import { usePagination } from "../hooks/usePagination";
import { usePowerStats } from "../hooks/usePowerStats";

const HomePage = ({ pokemons }: { pokemons: Pokemon[] }) => {
  const { filteredPokemons, search, setSearch, power, setPower } = useFilteredPokemons(pokemons);
  const { paginatedData: paginatedPokemons, currentPage, totalPages, goToPage } = usePagination(filteredPokemons, 20);
  const { minPower, maxPower } = usePowerStats(filteredPokemons);

  return (
    <>
      <Head>
        <title>Technical test next.js and typescript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl">Pokemon list</h1>

      <div className="flex w-full items-center space-x-2">
        <SearchInput search={search} onChange={setSearch} />
        <PowerThresholdInput power={power} onChange={setPower} />
      </div>
      <StatsDisplay count={filteredPokemons.length} minPower={minPower} maxPower={maxPower} />
      <PaginationControls currentPage={currentPage} totalPages={totalPages} onPageChange={goToPage} />
      <PokemonTable pokemons={paginatedPokemons} />
    </>
  );
};

HomePage.getLayout = Layout;

export async function getServerSideProps() {
  try {
    const pokemons = await fetch("http://localhost:3000/api/pokemons").then((resp) => resp.json());
    return { props: { pokemons } };
  } catch (error) {
    return {
      notFound: true,
    };
  }
}

export default HomePage;
